### ISSUE TITLE
Ethereum Issue

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#199]
I get errors when creating spaces, or account or when making transactions

SEE ERROR MESSAGES BELOW IN COMMENT

**Comment by KarimChabrak** [comment]
**WHEN MAKING TRANSACTIONS FOLLOWING ERROR**

{
    "url": "/u/Bot001/xcoin/transaction/transfer?accountId=7738",
    "status": 500,
    "response": {
        "error": true,
        "message": "Could not do transfer coins, will fix this ASAP !"
    },
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "{\"error\":true,\"message\":\"Could not do transfer coins, will fix this ASAP !\"}",
        "responseJSON": {
            "error": true,
            "message": "Could not do transfer coins, will fix this ASAP !"
        },
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "dataType": "json",
    "error": true,
    "message": "Could not do transfer coins, will fix this ASAP !",
    "errorThrown": "Internal Server Error",
    "validationError": false
}

**Comment by KarimChabrak** [comment]
**WHEN CREATING AN ACCOUNT WITHIN A SPACE FOLLOWING ERROR**

An unexpected server error occurred. If this keeps happening, please contact a site administrator.
{
    "url": "/s/testing-ethereum-smart-contract/xcoin/account/edit",
    "status": 500,
    "response": "<pre>PHP Notice &#039;yii\\base\\ErrorException&#039; with message &#039;Undefined property: stdClass::$address&#039; \n\nin /var/www/coinsence/protected/modules/ethereum/calls/Wallet.php:52\n\nStack trace:\n#0 /var/www/coinsence/protected/modules/ethereum/calls/Wallet.php(52): yii\\base\\ErrorHandler-&gt;handleError(8, &#039;Undefined prope...&#039;, &#039;/var/www/coinse...&#039;, 52, Array)\n#1 [internal function]: humhub\\modules\\ethereum\\calls\\Wallet::createWallet(Object(yii\\base\\ModelEvent))\n#2 /var/...",
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "<pre>PHP Notice &#039;yii\\base\\ErrorException&#039; with message &#039;Undefined property: stdClass::$address&#039; \n\nin /var/www/coinsence/protected/modules/ethereum/calls/Wallet.php:52\n\nStack trace:\n#0 /var/www/coinsence/protected/modules/ethereum/calls/Wallet.php(52): yii\\base\\ErrorHandler-&gt;handleError(8, &#039;Undefined prope...&#039;, &#039;/var/www/coinse...&#039;, 52, Array)\n#1 [internal function]: humhub\\modules\\ethereum\\calls\\Wallet::createWallet(Object(yii\\base\\ModelEvent))\n#2 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Array, Object(yii\\base\\ModelEvent))\n#3 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\\base\\Event::trigger(&#039;humhub\\\\modules\\\\...&#039;, &#039;beforeValidate&#039;, Object(yii\\base\\ModelEvent))\n#4 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Model.php(385): yii\\base\\Component-&gt;trigger(&#039;beforeValidate&#039;, Object(yii\\base\\ModelEvent))\n#5 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Model.php(350): yii\\base\\Model-&gt;beforeValidate()\n#6 /var/www/coinsence/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(504): yii\\base\\Model-&gt;validate(NULL)\n#7 /var/www/coinsence/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(670): yii\\db\\ActiveRecord-&gt;insert(true, NULL)\n#8 /var/www/coinsence/protected/modules/xcoin/controllers/AccountController.php(68): yii\\db\\BaseActiveRecord-&gt;save()\n#9 [internal function]: humhub\\modules\\xcoin\\controllers\\AccountController-&gt;actionEdit()\n#10 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)\n#11 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction-&gt;runWithParams(Array)\n#12 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\\base\\Controller-&gt;runAction(&#039;edit&#039;, Array)\n#13 /var/www/coinsence/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module-&gt;runAction(&#039;xcoin/account/e...&#039;, Array)\n#14 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\\web\\Application-&gt;handleRequest(Object(humhub\\components\\Request))\n#15 /var/www/coinsence/index.php(25): yii\\base\\Application-&gt;run()\n#16 {main}</pre>",
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "dataType": "html",
    "html": "<pre>PHP Notice &#039;yii\\base\\ErrorException&#039; with message &#039;Undefined property: stdClass::$address&#039; \n\nin /var/www/coinsence/protected/modules/ethereum/calls/Wallet.php:52\n\nStack trace:\n#0 /var/www/coinsence/protected/modules/ethereum/calls/Wallet.php(52): yii\\base\\ErrorHandler-&gt;handleError(8, &#039;Undefined prope...&#039;, &#039;/var/www/coinse...&#039;, 52, Array)\n#1 [internal function]: humhub\\modules\\ethereum\\calls\\Wallet::createWallet(Object(yii\\base\\ModelEvent))\n#2 /var/...",
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}

**Comment by KarimChabrak** [comment]
**when creating a space (Space is created, but no default account or smart contract) following error**
{
    "url": "/space/create/create",
    "status": 500,
    "response": "<pre>PHP Notice &#039;yii\\base\\ErrorException&#039; with message &#039;Undefined property: stdClass::$address&#039; \n\nin /var/www/coinsence/protected/modules/ethereum/calls/Wallet.php:52\n\nStack trace:\n#0 /var/www/coinsence/protected/modules/ethereum/calls/Wallet.php(52): yii\\base\\ErrorHandler-&gt;handleError(8, &#039;Undefined prope...&#039;, &#039;/var/www/coinse...&#039;, 52, Array)\n#1 [internal function]: humhub\\modules\\ethereum\\calls\\Wallet::createWallet(Object(yii\\base\\ModelEvent))\n#2 /var/...",
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "<pre>PHP Notice &#039;yii\\base\\ErrorException&#039; with message &#039;Undefined property: stdClass::$address&#039; \n\nin /var/www/coinsence/protected/modules/ethereum/calls/Wallet.php:52\n\nStack trace:\n#0 /var/www/coinsence/protected/modules/ethereum/calls/Wallet.php(52): yii\\base\\ErrorHandler-&gt;handleError(8, &#039;Undefined prope...&#039;, &#039;/var/www/coinse...&#039;, 52, Array)\n#1 [internal function]: humhub\\modules\\ethereum\\calls\\Wallet::createWallet(Object(yii\\base\\ModelEvent))\n#2 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Array, Object(yii\\base\\ModelEvent))\n#3 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\\base\\Event::trigger(&#039;humhub\\\\modules\\\\...&#039;, &#039;beforeValidate&#039;, Object(yii\\base\\ModelEvent))\n#4 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Model.php(385): yii\\base\\Component-&gt;trigger(&#039;beforeValidate&#039;, Object(yii\\base\\ModelEvent))\n#5 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Model.php(350): yii\\base\\Model-&gt;beforeValidate()\n#6 /var/www/coinsence/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(504): yii\\base\\Model-&gt;validate(NULL)\n#7 /var/www/coinsence/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(670): yii\\db\\ActiveRecord-&gt;insert(true, NULL)\n#8 /var/www/coinsence/protected/modules/xcoin/helpers/AccountHelper.php(35): yii\\db\\BaseActiveRecord-&gt;save()\n#9 /var/www/coinsence/protected/humhub/modules/space/models/Space.php(245): humhub\\modules\\xcoin\\helpers\\AccountHelper::initContentContainer(Object(humhub\\modules\\space\\models\\Space))\n#10 /var/www/coinsence/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(555): humhub\\modules\\space\\models\\Space-&gt;afterSave(true, Array)\n#11 /var/www/coinsence/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(510): yii\\db\\ActiveRecord-&gt;insertInternal(NULL)\n#12 /var/www/coinsence/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(670): yii\\db\\ActiveRecord-&gt;insert(true, NULL)\n#13 /var/www/coinsence/protected/humhub/modules/space/controllers/CreateController.php(67): yii\\db\\BaseActiveRecord-&gt;save()\n#14 [internal function]: humhub\\modules\\space\\controllers\\CreateController-&gt;actionCreate(NULL, 0)\n#15 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)\n#16 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction-&gt;runWithParams(Array)\n#17 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\\base\\Controller-&gt;runAction(&#039;create&#039;, Array)\n#18 /var/www/coinsence/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module-&gt;runAction(&#039;space/create/cr...&#039;, Array)\n#19 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\\web\\Application-&gt;handleRequest(Object(humhub\\components\\Request))\n#20 /var/www/coinsence/index.php(25): yii\\base\\Application-&gt;run()\n#21 {main}</pre>",
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "dataType": "html",
    "html": "<pre>PHP Notice &#039;yii\\base\\ErrorException&#039; with message &#039;Undefined property: stdClass::$address&#039; \n\nin /var/www/coinsence/protected/modules/ethereum/calls/Wallet.php:52\n\nStack trace:\n#0 /var/www/coinsence/protected/modules/ethereum/calls/Wallet.php(52): yii\\base\\ErrorHandler-&gt;handleError(8, &#039;Undefined prope...&#039;, &#039;/var/www/coinse...&#039;, 52, Array)\n#1 [internal function]: humhub\\modules\\ethereum\\calls\\Wallet::createWallet(Object(yii\\base\\ModelEvent))\n#2 /var/...",
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}
