### ISSUE TITLE
Task module update

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#243]
The current task module on prod is not yet updated based on I4C work.

**Comment by KarimChabrak** [comment]
@gdalyy 

I get gollowing error when creating task

An unexpected server error occurred. If this keeps happening, please contact a site administrator.

{
    "url": "/space/coinsence-project/tasks/task/edit?cal=0&listId=40",
    "status": 500,
    "response": "<pre>Exception (Unknown Property) &#039;yii\\base\\UnknownPropertyException&#039; with message &#039;Setting unknown property: humhub\\modules\\tasks\\models\\Task::has_account&#039; \n\nin /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Component.php:209\n\nStack trace:\n#0 /var/www/coinsence/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(322): yii\\base\\Component-&gt;__set(&#039;has_account&#039;, &#039;1&#039;)\n#1 /var/www/coinsence/protected/modules/tasks/models/Task.php(204): yii\\db\\BaseAc...",
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "<pre>Exception (Unknown Property) &#039;yii\\base\\UnknownPropertyException&#039; with message &#039;Setting unknown property: humhub\\modules\\tasks\\models\\Task::has_account&#039; \n\nin /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Component.php:209\n\nStack trace:\n#0 /var/www/coinsence/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(322): yii\\base\\Component-&gt;__set(&#039;has_account&#039;, &#039;1&#039;)\n#1 /var/www/coinsence/protected/modules/tasks/models/Task.php(204): yii\\db\\BaseActiveRecord-&gt;__set(&#039;has_account&#039;, &#039;1&#039;)\n#2 /var/www/coinsence/protected/modules/tasks/models/forms/TaskForm.php(247): humhub\\modules\\tasks\\models\\Task-&gt;__set(&#039;has_account&#039;, &#039;1&#039;)\n#3 /var/www/coinsence/protected/modules/tasks/controllers/TaskController.php(77): humhub\\modules\\tasks\\models\\forms\\TaskForm-&gt;load(Array)\n#4 [internal function]: humhub\\modules\\tasks\\controllers\\TaskController-&gt;actionEdit(NULL, &#039;0&#039;, false, &#039;40&#039;)\n#5 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)\n#6 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction-&gt;runWithParams(Array)\n#7 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\\base\\Controller-&gt;runAction(&#039;edit&#039;, Array)\n#8 /var/www/coinsence/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module-&gt;runAction(&#039;tasks/task/edit&#039;, Array)\n#9 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\\web\\Application-&gt;handleRequest(Object(humhub\\components\\Request))\n#10 /var/www/coinsence/index.php(27): yii\\base\\Application-&gt;run()\n#11 {main}</pre>",
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "dataType": "html",
    "html": "<pre>Exception (Unknown Property) &#039;yii\\base\\UnknownPropertyException&#039; with message &#039;Setting unknown property: humhub\\modules\\tasks\\models\\Task::has_account&#039; \n\nin /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Component.php:209\n\nStack trace:\n#0 /var/www/coinsence/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(322): yii\\base\\Component-&gt;__set(&#039;has_account&#039;, &#039;1&#039;)\n#1 /var/www/coinsence/protected/modules/tasks/models/Task.php(204): yii\\db\\BaseAc...",
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}
