### ISSUE TITLE
Add transaction confirmation

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#313]
After performing a transaction, I would like to see a popup telling me that 

![grafik](https://user-images.githubusercontent.com/41925899/131379445-4bbedce9-6d14-4efa-aace-646363d0ec7e.png)

In case of donation to projects, i would like to see this
![grafik](https://user-images.githubusercontent.com/41925899/131380458-17d3370b-bd8e-4d1e-83ef-6245b3aeae0f.png)

**Comment by KarimChabrak** [comment]
When investing in project, i get an error message. (INVESTMENT SID WORK)
@gdalyy  

{
    "url": "/space/test-accept-funding/xcoin/funding/invest?fundingId=181&accountId=247",
    "status": 500,
    "response": "<pre>PHP Notice &#039;yii\\base\\ErrorException&#039; with message &#039;Undefined variable: transaction&#039; \n\nin /var/www/coinsence_dev/protected/modules/xcoin/views/funding/invest-overview.php:55\n\nStack trace:\n#0 /var/www/coinsence_dev/protected/modules/xcoin/views/funding/invest-overview.php(55): yii\\base\\ErrorHandler-&gt;handleError(8, &#039;Undefined varia...&#039;, &#039;/var/www/coinse...&#039;, 55, Array)\n#1 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/View.php(336): require...",
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "<pre>PHP Notice &#039;yii\\base\\ErrorException&#039; with message &#039;Undefined variable: transaction&#039; \n\nin /var/www/coinsence_dev/protected/modules/xcoin/views/funding/invest-overview.php:55\n\nStack trace:\n#0 /var/www/coinsence_dev/protected/modules/xcoin/views/funding/invest-overview.php(55): yii\\base\\ErrorHandler-&gt;handleError(8, &#039;Undefined varia...&#039;, &#039;/var/www/coinse...&#039;, 55, Array)\n#1 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/View.php(336): require(&#039;/var/www/coinse...&#039;)\n#2 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/View.php(254): yii\\base\\View-&gt;renderPhpFile(&#039;/var/www/coinse...&#039;, Array)\n#3 /var/www/coinsence_dev/protected/humhub/modules/ui/view/components/View.php(111): yii\\base\\View-&gt;renderFile(&#039;/var/www/coinse...&#039;, Array, Object(humhub\\modules\\xcoin\\controllers\\FundingController))\n#4 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/web/Controller.php(49): humhub\\modules\\ui\\view\\components\\View-&gt;renderAjax(&#039;invest-overview&#039;, Array, Object(humhub\\modules\\xcoin\\controllers\\FundingController))\n#5 /var/www/coinsence_dev/protected/modules/xcoin/controllers/FundingController.php(127): yii\\web\\Controller-&gt;renderAjax(&#039;invest-overview&#039;, Array)\n#6 [internal function]: humhub\\modules\\xcoin\\controllers\\FundingController-&gt;actionInvest(&#039;181&#039;)\n#7 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)\n#8 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction-&gt;runWithParams(Array)\n#9 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\\base\\Controller-&gt;runAction(&#039;invest&#039;, Array)\n#10 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module-&gt;runAction(&#039;xcoin/funding/i...&#039;, Array)\n#11 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\\web\\Application-&gt;handleRequest(Object(humhub\\components\\Request))\n#12 /var/www/coinsence_dev/index.php(31): yii\\base\\Application-&gt;run()\n#13 {main}</pre>",
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "dataType": "html",
    "html": "<pre>PHP Notice &#039;yii\\base\\ErrorException&#039; with message &#039;Undefined variable: transaction&#039; \n\nin /var/www/coinsence_dev/protected/modules/xcoin/views/funding/invest-overview.php:55\n\nStack trace:\n#0 /var/www/coinsence_dev/protected/modules/xcoin/views/funding/invest-overview.php(55): yii\\base\\ErrorHandler-&gt;handleError(8, &#039;Undefined varia...&#039;, &#039;/var/www/coinse...&#039;, 55, Array)\n#1 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/View.php(336): require...",
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}
