### ISSUE TITLE
User log in  and registration from IBB.

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#316]
I would like to get a popup directly on http://beyondborders.network when clicking on "register" or "login"

User shall be directed automatically to Beyond Borders space landing page. 

![grafik](https://user-images.githubusercontent.com/41925899/131711145-a2302dd1-2eb6-408d-9e9c-e3d6b2edeab1.png)

![grafik](https://user-images.githubusercontent.com/41925899/131711346-b8435a1e-d3de-4eb8-aec9-5e7c07f3d00c.png)

Normally, these popups are accessible from https://community.coinsence.org/space/beyond-borders/ when user is not logged in. 

We might need to further add the possibility to customize the link where user get automatically directed after login. 

![grafik](https://user-images.githubusercontent.com/41925899/131884755-582a8ae8-9293-4d00-ba93-93dbb155ff5f.png)

**Comment by KarimChabrak** [comment]
**@craxrev we have foll0wing error on IBB space, when users are registered but not members yet.**


yii\base\ErrorException: Trying to get property 'status' of non-object in /var/www/coinsence/protected/modules/custom_pages/views/custom/container_pages/template_ibb_landing.php:189
Stack trace:
#0 /var/www/coinsence/protected/modules/custom_pages/views/custom/container_pages/template_ibb_landing.php(189): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/var/www/coinse...', 189, Array)
#1 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/View.php(336): require('/var/www/coinse...')
#2 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/var/www/coinse...', Array)
#3 /var/www/coinsence/protected/modules/custom_pages/views/container/php.php(25): yii\base\View->renderFile('/var/www/coinse...', Array)
#4 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/View.php(336): require('/var/www/coinse...')
#5 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/var/www/coinse...', Array)
#6 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/coinse...', Array, Object(humhub\modules\custom_pages\controllers\ContainerController))
#7 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Controller.php(384): yii\base\View->render('php', Array, Object(humhub\modules\custom_pages\controllers\ContainerController))
#8 /var/www/coinsence/protected/modules/custom_pages/controllers/ContainerController.php(79): yii\base\Controller->render('php', Array)
#9 [internal function]: humhub\modules\custom_pages\controllers\ContainerController->actionView()
#10 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('view', Array)
#13 /var/www/coinsence/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('custom_pages/co...', Array)
#14 /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#15 /var/www/coinsence/index.php(31): yii\base\Application->run()
#16 {main}
Copy StacktraceSearch StackoverflowSearch GoogleError
PHP Notice – yii\base\ErrorException
Trying to get property 'status' of non-object
1. in /var/www/coinsence/protected/modules/custom_pages/views/custom/container_pages/template_ibb_landing.phpat line 189
180181182183184185186187188189190191192193194195196197198                                <div class="logged-in">
                <div class="hero">
                    <h1>
                        <span>We are <br> a global network of</span><br>
                        Innovators & <br> social entrepreneurs.
                    </h1>
                    <p>
                        Initiated by Tunisian diaspora and local change-makers with the vision to Remove borders and build an open and decentral governed collaboration network that stimulates a more inclusive and sustainable economy that is build on participation and sharing.
                    </p>
                    <?php if (!$membership->status): ?>
                        <a class="primary" href="/space/testing-space/space/membership/request-membership-form" data-target="#globalModal">Join in</a>
                    <?php endif; ?>
                </div>
                <div class="sections">
                    <div class="section">
                        <h2>Create</h2>
                        <p>
                            Add your project to receive Tunisia Impact COIN that you can use to reward your donors and supporters.
                        </p>
                
2. in /var/www/coinsence/protected/modules/custom_pages/views/custom/container_pages/template_ibb_landing.php at line 189– yii\base\ErrorHandler::handleError(8, 'Trying to get property 'status' ...', '/var/www/coinsence/protected/mod...', 189, ...)
183184185186187188189190191192193194195                                            <span>We are <br> a global network of</span><br>
                        Innovators & <br> social entrepreneurs.
                    </h1>
                    <p>
                        Initiated by Tunisian diaspora and local change-makers with the vision to Remove borders and build an open and decentral governed collaboration network that stimulates a more inclusive and sustainable economy that is build on participation and sharing.
                    </p>
                    <?php if (!$membership->status): ?>
                        <a class="primary" href="/space/testing-space/space/membership/request-membership-form" data-target="#globalModal">Join in</a>
                    <?php endif; ?>
                </div>
                <div class="sections">
                    <div class="section">
                        <h2>Create</h2>
                
3. in /var/www/coinsence/protected/vendor/yiisoft/yii2/base/View.php at line 336– require('/var/www/coinsence/protected/mod...')
4. in /var/www/coinsence/protected/vendor/yiisoft/yii2/base/View.php at line 254– yii\base\View::renderPhpFile('/var/www/coinsence/protected/mod...', ['contentContainer' => humhub\modules\space\models\Space])
5. in /var/www/coinsence/protected/modules/custom_pages/views/container/php.php at line 25– yii\base\View::renderFile('/var/www/coinsence/protected/mod...', ['contentContainer' => humhub\modules\space\models\Space])
19202122232425262728293031                     
<div class="container <?= Html::encode($cssClass) ?>">
    <div class="row">
 
        <div class="col-md-12">
            <?php try { ?>
                <?= $this->renderFile($page->getPhpViewFilePath(), ['contentContainer' => $contentContainer]) ?>
            <?php } catch (ViewNotFoundException $vnfe) { ?>
                <?= Yii::t('CustomPagesModule.view_php', 'View not found') ?>
            <?php } ?>
        </div>
    </div>
</div>                
6. in /var/www/coinsence/protected/vendor/yiisoft/yii2/base/View.php at line 336– require('/var/www/coinsence/protected/mod...')
7. in /var/www/coinsence/protected/vendor/yiisoft/yii2/base/View.php at line 254– yii\base\View::renderPhpFile('/var/www/coinsence/protected/mod...', ['page' => humhub\modules\custom_pages\models\ContainerPage, 'contentContainer' => humhub\modules\space\models\Space])
8. in /var/www/coinsence/protected/vendor/yiisoft/yii2/base/View.php at line 156– yii\base\View::renderFile('/var/www/coinsence/protected/mod...', ['page' => humhub\modules\custom_pages\models\ContainerPage, 'contentContainer' => humhub\modules\space\models\Space], humhub\modules\custom_pages\controllers\ContainerController)
9. in /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Controller.php at line 384– yii\base\View::render('php', ['page' => humhub\modules\custom_pages\models\ContainerPage, 'contentContainer' => humhub\modules\space\models\Space], humhub\modules\custom_pages\controllers\ContainerController)
10. in /var/www/coinsence/protected/modules/custom_pages/controllers/ContainerController.php at line 79– yii\base\Controller::render('php', ['page' => humhub\modules\custom_pages\models\ContainerPage, 'contentContainer' => humhub\modules\space\models\Space])
73747576777879808182838485                                return $this->viewTemplatePage($page);
        } elseif ($page->type == Container::TYPE_HTML) {
            return $this->render('html', ['page' => $page, 'html' => $page->page_content, 'title' => $page->title]);
        } elseif ($page->type == Container::TYPE_PHP) {
            return $this->render('php', [
                'page' => $page,
                'contentContainer' => $this->contentContainer]);
        } else {
            throw new HttpException('500', 'Invalid page type!');
        }
    }
 
    /**
                
11. humhub\modules\custom_pages\controllers\ContainerController::actionView()
12. in /var/www/coinsence/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 57– call_user_func_array([humhub\modules\custom_pages\controllers\ContainerController, 'actionView'], [])
13. in /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Controller.php at line 157– yii\base\InlineAction::runWithParams(['id' => '26', 'cguid' => '1560c08a-3284-475b-ab22-361b9962...'])
14. in /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Module.php at line 528– yii\base\Controller::runAction('view', ['id' => '26', 'cguid' => '1560c08a-3284-475b-ab22-361b9962...'])
15. in /var/www/coinsence/protected/vendor/yiisoft/yii2/web/Application.php at line 103– yii\base\Module::runAction('custom_pages/container/view', ['id' => '26', 'cguid' => '1560c08a-3284-475b-ab22-361b9962...'])
16. in /var/www/coinsence/protected/vendor/yiisoft/yii2/base/Application.php at line 386– yii\web\Application::handleRequest(humhub\components\Request)
17. in /var/www/coinsence/index.php at line 31– yii\base\Application::run()
25262728293031                        (is_readable(__DIR__ . '/protected/config/web.php')) ? require(__DIR__ . '/protected/config/web.php') : []
);
 
$dotenv = new Dotenv();
$dotenv->load(__DIR__.'/.env');
 
(new humhub\components\Application($config))->run();
                
$_GET = [
    'id' => '26',
    'cguid' => '1560c08a-3284-475b-ab22-361b9962f03c',
];

$_COOKIE = [
    'language' => 'e9480a16dca13979f7616ad115e289c06b7301df3d6f05c849097c10e7fadd84a:2:{i:0;s:8:"language";i:1;s:5:"en_gb";}',
    '_ga' => 'GA1.2.275330535.1620141749',
    'pm_new-people-panel' => 'expanded',
    'pm_new-spaces-panel' => 'expanded',
    'PHPSESSID' => 'b60mded00ii4d5fvlshj4m23tf',
    '_identity' => '0b3e21a9c054ad37a7a83954f6d1a7e7921abf73b93e85b5745f93cffa6c91f1a:2:{i:0;s:9:"_identity";i:1;s:53:"[2413,"ff6878ae-c66d-42fa-9bf5-c45b506fc5de",2592000]";}',
    '_csrf' => 'e3928f06db5248e54f7a6574986e0a32086bdf14562eb860617184ff34c5bda3a:2:{i:0;s:5:"_csrf";i:1;s:32:"UvBpfH8AaU4qW_7tuSbiR3Dycia33IsH";}',
    'pm_panel-activities' => 'expanded',
];

$_SESSION = [
    '__flash' => [],
    '__id' => 2413,
    '__expire' => 1631044370,
    'currentAuthClientId' => 'local',
    'user.canSeeAdminSection' => false,
    'live.poll.lastQueryTime' => 1631042967,
];
Yii Framework
2021-09-07, 21:29:30

Apache/2.4.29 (Ubuntu)

Yii Framework/2.0.15

**Comment by KarimChabrak** [comment]
After direction from IBB, when adding my email to register, I get directed to Coinsence site?

INstead of "BACK HOME" i need only the option to close popup.

![grafik](https://user-images.githubusercontent.com/41925899/132401350-a9b7a806-1c85-4c52-bf5e-fd1151c27a6a.png)


![grafik](https://user-images.githubusercontent.com/41925899/132401373-5b3ec8fa-1cc7-43c3-a413-91688c343b9c.png)

**Comment by KarimChabrak** [comment]
Check as well following issue
https://github.com/Coinsence/meta/issues/324
